Added support for getreceivedbyaddress.
prasos/bittiraha-walletd pull request #5
Opened 2016-10-08 07:50 UTC by polac

2016-10-08 09:29 UTC, jojkaart requested changes

2016-10-08 09:29 UTC, jojkaart commented on src/fi/bittiraha/walletd/WalletRPC.java
> +	List<TransactionOutput> unspent = kit.wallet().calculateAllSpendCandidates(false, false);
calculateAllSpendCandidates returns a list of unspent outputs. You'll need to scan all transactions to implement the equivalent of bitcoind does.

2016-10-10 09:56 UTC, jojkaart commented
This looks almost perfect now. But it's still different from the bitcoind implementation. 
Basically two differences are still there:
1) There's no support for specifying the minconf parameter
2) bitcoind calculates the amount with minconf = 1 when it's ot specified. This code does the same as minconf=0.

Could you fix these two differences? I can then merge this.

2016-10-16 10:24 UTC, polac commented
1) added
2) It doesn't matter anymore but just wanted mention that my previous implementation was only accepting transactions which have minconf=1. I was only using pools SPENT and UNSPENT. Transaction can be in those pools only after it has at least 1 conf. Or have I misunderstood the way pools work. Anyways, doesn't matter anymore.

2016-10-20 11:48 UTC, merged

2016-10-20 11:52 UTC, jojkaart commented
This pull request has now been merged. Thank you for the contribution.